// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8lwOHeXaefVxJhYg4l2l-vQdR0qpkII',
    appId: '1:384180080362:web:baa6bf97b7db5910f9d193',
    messagingSenderId: '384180080362',
    projectId: 'cp-project-4a907',
    authDomain: 'cp-project-4a907.firebaseapp.com',
    storageBucket: 'cp-project-4a907.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuIYr3cgfoMg6c1wF_eQZWOc3frsvFK4',
    appId: '1:384180080362:android:e03abf4b65514fdaf9d193',
    messagingSenderId: '384180080362',
    projectId: 'cp-project-4a907',
    storageBucket: 'cp-project-4a907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWruIqclfDazhUKdhQP2g8_mvX3YHII9E',
    appId: '1:384180080362:ios:e26e4047cf594dc2f9d193',
    messagingSenderId: '384180080362',
    projectId: 'cp-project-4a907',
    storageBucket: 'cp-project-4a907.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWruIqclfDazhUKdhQP2g8_mvX3YHII9E',
    appId: '1:384180080362:ios:e26e4047cf594dc2f9d193',
    messagingSenderId: '384180080362',
    projectId: 'cp-project-4a907',
    storageBucket: 'cp-project-4a907.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC8lwOHeXaefVxJhYg4l2l-vQdR0qpkII',
    appId: '1:384180080362:web:a928973b72720e4bf9d193',
    messagingSenderId: '384180080362',
    projectId: 'cp-project-4a907',
    authDomain: 'cp-project-4a907.firebaseapp.com',
    storageBucket: 'cp-project-4a907.firebasestorage.app',
  );
}
